### ISSUE TITLE
Environment variables

### ISSUE THREAD

**Issue by shubham101096** [catherineisonline/pizza-time-with-react#7]
Hi. What value to set for the env like REACT_APP_USERS_URL and REACT_APP_DATABASE_URL? Also will this code work with any mysql database without code modifations? Where do we need to mention the database url and database password. Thanks.

**Comment by catherineisonline** [comment]
REACT_APP_USERS_URL is the backend, you can set it locally like http://localhost:3000/users or any server URL you set.
REACT_APP_DATABASE_URL is my personal URL to connect to the PlanetScale database, you need to create your own account and connect to your database. You can read the docs here https://planetscale.com/docs/tutorials/connect-any-application

**Comment by shubham101096** [comment]
How to run the backend folder in your code? I think when we execute npm start only frontend server starts. Also, are the order details stored in database on checkout?

**Comment by catherineisonline** [comment]
No, the order details are not saved, the database is used only for the user login/registration. You can run the server locally so set the REACT_APP_USERS_URL to localhost and change the pizza-time-backend.vercel.com link to localhost as well.  Otherwise you should set up your own backed, I use Vercel for that, you can find the guides to do that here: https://www.google.com/search?q=how+to+set+up+backend+with+vercel&sca_esv=577627317&ei=aoU-ZdmkJKXg7_UPhpynwAo&ved=0ahUKEwjZgZf605uCAxUl8LsIHQbOCagQ4dUDCBA&uact=5&oq=how+to+set+up+backend+with+vercel&gs_lp=Egxnd3Mtd2l6LXNlcnAiIWhvdyB0byBzZXQgdXAgYmFja2VuZCB3aXRoIHZlcmNlbDIFEAAYogQyBRAAGKIEMgUQABiiBDIFEAAYogRIjwtQ0wRY9wVwAHgCkAEAmAHCAaABgAOqAQMwLjK4AQPIAQD4AQHCAgQQABhH4gMEGAAgQYgGAZAGCA&sclient=gws-wiz-serp
